### ISSUE TITLE
compile problem

### ISSUE THREAD

**Issue by intoucable** [zang09/ORB_SLAM3_ROS2#3]
/usr/local/include/sophus/common.hpp:36:10: fatal error: fmt/format.h: No such file or directory
  36 | #include <fmt/format.h>

hi, i got this problem when compiling the project, i do install Sophus, but it seems like something wrong with Sophus,
how should i deal with it ?

**Comment by intoucable** [comment]
i installed orbslam3  built-in Sophus library and fixed it

**Comment by Yyote** [comment]
> i installed orbslam3 built-in Sophus library and fixed it

Where did you find it? I tried building it from source from a github repo but all I got was a ton of redefenitions whene trying to build the ros package
