### ISSUE TITLE
undefined reference to symbol '_ZN2cv23initUndistortRectifyMapERKNS_11_InputArrayES2_S2_S2_NS_5Size_IiEEiRKNS_12_OutputArrayES7_' /usr/bin/ld: /lib/x86_64-linux-gnu/libopencv_calib3d.so.4.5d: error adding symbols: DSO missing from command line

### ISSUE THREAD

**Issue by andremaurell** [zang09/ORB_SLAM3_ROS2#30]
![Screenshot from 2024-07-03 12-03-04](https://github.com/zang09/ORB_SLAM3_ROS2/assets/90858902/fe7d8c33-6437-45e6-ac74-352147a3a94a)

**Comment by andremaurell** [comment]
I'm trying to build the package on ubuntu 22.04, ros humble and receive that error

**Comment by IaroslavS** [comment]
I faced the same problem. Solved with checkout to "humble" branch in this repo. Another solve is to rm -rf build/ install/ log/ in colcon_ws
