### ISSUE TITLE
Error to run monocular: Failed to open settings file at: orbslam3_ros2/config/monocular/TUM1.yaml

### ISSUE THREAD

**Issue by andremaurell** [zang09/ORB_SLAM3_ROS2#31]
![image](https://github.com/zang09/ORB_SLAM3_ROS2/assets/90858902/093781a1-399b-4578-823b-8eb6be1bb09a)

**Comment by Ehnodoh** [comment]
Hi @andremaurell ! 
I have the same problem! What were your solution for this problem?

**Comment by 123orrin** [comment]
I had this same issue. Fixed it by specifying the absolute path to the file.

For example use `~/orbslam_ws/src/orbslam3_ros2/config/monocular/TUM1.yaml` instead of `orbslam3_ros2/config/monocular/TUM1.yaml`.
