### ISSUE TITLE
/usr/bin/ld: /usr/local/lib/libopencv_calib3d.so.407: error adding symbols: DSO missing from command line

### ISSUE THREAD

**Issue by weiwei-dotcom** [zang09/ORB_SLAM3_ROS2#5]
![截图 2023-04-03 20-56-48](https://user-images.githubusercontent.com/62756096/229516502-7e9d7f3f-fecb-4ba0-9d38-63c755877fad.png)
what's wrong with this error?

**Comment by zang09** [comment]
Hi, may be you are not build with `OpenCV 4.2.0` version.

**Comment by 1347849769** [comment]
I have the same question

**Comment by 1347849769** [comment]
> ![截图 2023-04-03 20-56-48](https://user-images.githubusercontent.com/62756096/229516502-7e9d7f3f-fecb-4ba0-9d38-63c755877fad.png)
> what's wrong with this error?
the ros2 version must be foxy,

> ![截图 2023-04-03 20-56-48](https://user-images.githubusercontent.com/62756096/229516502-7e9d7f3f-fecb-4ba0-9d38-63c755877fad.png)
> what's wrong with this error?
This is not a problem with opencv. Maybe your ros2 version is not foxy. I changed the Ubuntu system to 20.04 and used the foxy version of ros2 to compile normally

**Comment by 1347849769** [comment]
> ![截图 2023-04-03 20-56-48](https://user-images.githubusercontent.com/62756096/229516502-7e9d7f3f-fecb-4ba0-9d38-63c755877fad.png)
> 这个错误有什么问题？
This is not a problem with opencv. Maybe your ros2 version is not foxy. I changed the Ubuntu system to 20.04 and used the foxy version of ros2 to compile normally

**Comment by EndlessLoops** [comment]
https://github.com/alsora/ros2-ORB_SLAM2/issues/8#issuecomment-1461570970

**Comment by Fran-FC** [comment]
I fixed it and created a pull request, try it if you are still interested

**Comment by hermanumrao** [comment]
> I fixed it and created a pull request, try it if you are still interested

I was gtting the same error
@Fran-FC  didn't see you pull request,
but then i just went your profile and copied your [cmakelists.txt](https://github.com/Fran-FC/ORB_SLAM3_ROS2/blob/main/CMakeLists.txt)  and now it works fine

thanks man
